apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - files:
      ## ---=======********** CUSTOM LOGIC SCRIPT **********=======---
      ## Only enable ONE of the following examples at a time
      ## ---=======********** CUSTOM LOGIC SCRIPT **********=======---

      ## Custom Dynamic Secret (Create/Delete Temp User)
      # - example-scripts/splunk_temp_user/custom_logic.sh                                 # Custom Dynamic Secret

      ## Custom Rotated Secret (Rotate Password)
      - example-scripts/random_rotated_password/custom_logic.sh # Custom Rotated Secret
      # - example-scripts/okta_rotated_password/custom_logic.sh                            # Custom Rotated Secret
      # - example-scripts/keycloak_rotate_admin_password/custom_logic.sh                   # Custom Rotated Secret
      # - example-scripts/heroku_push_rotated_creds/custom_logic.sh                        # Custom Rotated Secret
      # - example-scripts/legacy-azure-key-vault-svc-principal-rotation/custom_logic.sh    # Custom Rotated Secret
    name:
      akl-custom-script-configmap

      ## Place the Gateway Admin Access ID here of the ONLY Gateway that will be allowed to access this custom server
secretGenerator:
  - literals:
      ## Place the Gateway Admin Access ID here of the ONLY Gateway that will be allowed to trigger this custom server
      - GW_ACCESS_ID=p-om5l3****jjk
    name: akl-gateway-access-id-secret

resources:
  - deployment.yml
  - service.yml
  # - ingress.yml
  # - example-scripts/legacy-azure-key-vault-svc-principal-rotation/azure-legacy-custom-sa.yml

# patches:
#   - path: example-scripts/legacy-azure-key-vault-svc-principal-rotation/patch-deployment.yml
